### ISSUE TITLE
find_pathways_by_xref server error 524

### ISSUE THREAD

**Issue by daniel-spies** [wikipathways/pywikipathways#10]
Hi there, 

I was trying to follow your tutorial to retrieve pathways of a gene of interest using the following code: 

`pwpw.find_pathways_by_xref('TNF','H')`

but only get the following error message:
`Error:  524 Server Error:  for url: https://webservice.wikipathways.org/findPathwaysByXref?ids=TNF&codes=H&format=json`

internally python throws an error due to an empty return value and not being able to produce a pandas df, but ultimately the empty data retrieval is the issue. Also when trying via the UI (to exclude issues with json or other modules) I get the same error though with a. bit more information:

Response Code
`524`

Response Headers
`
{
  "access-control-allow-origin": "*",
  "alt-svc": "h3=\":443\"; ma=86400",
  "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
  "cf-ray": "8ebc1620cb7429a5-ORD",
  "connection": "Keep-Alive",
  "content-length": "7141",
  "content-type": "text/html; charset=UTF-8",
  "date": "Mon, 02 Dec 2024 14:44:36 GMT",
  "expires": "Thu, 01 Jan 1970 00:00:01 GMT",
  "keep-alive": "timeout=5, max=100",
  "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "referrer-policy": "same-origin",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=G8XZjaeL8nA8K3UelEENkazoR9Rn8WnMWqtD3meRir51Vk10e2MRUn3dZlImQVFe24NK4zcw3RQwJmRubYlXLIIoyVhOASuTffKs7XK7GGt3ZM%2FP7ox1adE2AsdgMmiwWXZpnj0yV9urrXU%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "server": "cloudflare",
  "server-timing": "cfL4;desc=\"?proto=TCP&rtt=11826&min_rtt=9391&rtt_var=5268&sent=12&recv=14&lost=0&retrans=0&sent_bytes=12387&recv_bytes=4366&delivery_rate=912317&cwnd=256&unsent_bytes=0&cid=ef5a4adf79758614&ts=173343&x=0\"",
  "x-frame-options": "SAMEORIGIN"
}
`

is this a temporary issue with the servers or a systematic issue?

best
Daniel

**Comment by DrNamwob** [comment]
I'm getting the same error. I think it could be due to the WikiPathways website being updated to a new version. Perhaps the package is expecting the old verison.

**Comment by youphendriks** [comment]
@daniel-spies @DrNamwob tried reproducing the issue and it seems to work now.
The issue was most likely caused by server outage last week.
Is the issue still happening for you?

**Comment by daniel-spies** [comment]
It worked a few days later, as you said,  I also figured it was most likely
due to server capacities

Best
Daniel

**Comment by youphendriks** [comment]
Great, thank you for making the issue
I'll get this issue closed then
