### ISSUE TITLE
can't download pathway archive

### ISSUE THREAD

**Issue by wenyuhaokikika** [wikipathways/pywikipathways#8]
can't download pathway archive,why? `pwpw.__version__=0.0.2`
```
└─(14:53:39)──> proxychains python -c 'import pywikipathways as pwpw;pwpw.download_pathway_archive(organism="Homo sapiens", format="gmt")'                                                                 130 ↵ ──(Mon,Jul15)─┘
[proxychains] config file found: /data/wenyuhao/software/proxychains/proxychains.conf
[proxychains] preloading /data/wenyuhao/software/proxychains/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  10.20.213.73:10808  ...  webservice.wikipathways.org:443  ...  OK
[proxychains] Strict chain  ...  10.20.213.73:10808  ...  wikipathways-data.wmcloud.org:443  ...  OK
[proxychains] Strict chain  ...  10.20.213.73:10808  ...  wikipathways-data.wmcloud.org:80  ...  OK
[proxychains] Strict chain  ...  10.20.213.73:10808  ...  wikipathways-data.wmcloud.org:443  ...  OK
Could not find a file matching your specifications. Try browsing http://data.wikipathways.org.
```

**Comment by egonw** [comment]
@kozo2, looks like the code needs to be updated. (cc @AlexanderPico)

**Comment by kozo2** [comment]
@wenyuhaokikika @egonw Thanks for letting me know this. I will update the program. Give me some time.

**Comment by AlexanderPico** [comment]
@kozo2 You know about the new JSON-API for WikiPathways, right?  I updated the rWikiPathways package, so you might look there for examples...

https://github.com/wikipathways/rWikiPathways

Let me know if you have any questions.

**Comment by kozo2** [comment]
@AlexanderPico Thanks for the comment.
Yes, I know about the new JSON-API https://www.wikipathways.org/json/.
I will imitate https://github.com/wikipathways/rWikiPathways/blob/devel/R/listOrganisms.R and https://github.com/wikipathways/rWikiPathways/blob/devel/R/downloadPathwayArchive.R for new pywikipathways.

**Comment by kozo2** [comment]
Hi @wenyuhaokikika 
I fixed this issue at #9 and uploaded new version (0.0.3) to https://pypi.org/project/pywikipathways/ .
Thanks for flagging this. 🙏

**Comment by kozo2** [comment]
@wenyuhaokikika 
I created a Google Colab notebook for testing
`download_pathway_archive(organism="Homo sapiens", format="gmt")`.
Please find https://colab.research.google.com/drive/1n43f8gDbHDwkqaWMczMO_f6IUH4gTBAR?usp=sharing .

**Comment by wenyuhaokikika** [comment]
OK, thank you very much for your reply. The problem has been solved. Pywikipathways runs successfully in environments above 3.9. I will close this issue.
